name: ocr_yolox_plate
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.4
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  flutter_svg: ^2.0.10+1
  camera: ^0.11.0+1
  image: ^3.1.0
  uuid: ^4.4.0
  path_provider: ^2.1.3
  flutter_image_compress: ^1.1.3
  shared_preferences: ^2.2.3
  widget_circular_animator: ^1.0.0
  carousel_slider: ^4.2.1
  blurrycontainer: ^2.1.0
  ffi: ^2.1.2
  ncnn_yolox_flutter: ^0.4.2
  sqflite: ^2.3.3+1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/models/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/lexend/Lexend.ttf